namespace WannabeTrello.Domain.Enums;

public enum ActivityType
{
    ProjectCreated,
    ProjectUpdated,
    ProjectArchived,
    ProjectMemberAdded,
    ProjectMemberRoleUpdated,
    ProjectMemberRemoved,
    BoardCreated,
    BoardUpdated,
    BoardArchived,
    BoardRestored,
    TaskCreated,
    TaskUpdated,
    TaskMoved,
    TaskAssigned,
    TaskCompleted,
    CommentAdded,
    CommentUpdated,
    CommentDeleted,
    CommentRestored,
    BoardDeleted,
    ColumnAdded,
    ColumnUpdated,
    ColumnDeleted,
    ColumnOrderChanged,
    ColumnWipLimitChanged,
    UserInvited,
    UserJoinedBoard,
    UserRemovedFromBoard,
    UserProfileUpdated,
    UserDeactivated,
    UserReactivated,
}